// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckForUpdate():Promise<string>;

export function DoSelfUpdate():Promise<void>;

export function GetCurrentVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function TestDb():Promise<models.Connection>;
